#!/bin/sh

# Fetch added, copied, modified and renamed files
FILES=$(git diff --cached --name-only --diff-filter=ACMR "*.js" "*.jsx" "*.scss" "*.css" "*.json" | sed 's| |\\ |g')
[ -z "$FILES" ] && echo "No files were changed." && exit 0

# Prettify all selected files
echo "$FILES" | xargs ./node_modules/.bin/prettier --write

# Check if an error occurred while formatting the files
if [ $? -eq 0 ];
then
  # Add back the modified/prettified files to staging
  echo "$FILES" | xargs git add
  exit 0
else
  exit 1
fi
