name: Test-deploy ModuleSite

# Trigger the workflow on all pull requests
on: pull_request

jobs:
  # Trigger job i.e. build and run on the latest version of ubuntu
  build:
    runs-on: ubuntu-latest
    # Templates for building and releasing ModuleSite
    steps:
      - uses: actions/checkout@v3
      # Template to test-deploy ModuleSite
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install Project Dependencies
        run: yarn
      - name: Install Gatsby CLI
        run: yarn global add gatsby-cli@4.16.0
      - name: Start Development Server
        run: gatsby develop
