name: Test-Build ModuleSite

# Trigger the workflow on all pull requests
on: pull_request

jobs:
  gatsby-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v3
      - name: Install Project Dependencies
        run: yarn
      - name: Build ModuleSite
        run: yarn run build:pp
