name: Test-deploy ModuleSite

# Trigger the workflow on all pull requests
on: pull_request

jobs:
  # Trigger job i.e. build and run on the latest version of ubuntu
  build:
    runs-on: ubuntu-latest
    # Templates for building and releasing ModuleSite
    steps:
      - uses: actions/checkout@v2
      # Template to test-deploy ModuleSite
      - uses: jzweifel/gatsby-cli-github-action@v1.0.0
        with:
          # Arguments that get passed to gatsby CLI
          gatsby-args: develop
