name: Lint ModuleSite Code

# Trigger the workflow on all pull requests
on: pull_request

jobs:
  # Trigger job i.e. build and run on the latest version of ubuntu
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Project Dependencies
        run: yarn
      - name: Lint JavaScript
        run: yarn run lint:js
  remark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Project Dependencies
        run: yarn
      - name: Lint MarkDown
        run: yarn run lint:md
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Project Dependencies
        run: yarn
      - name: Validate JavaScript Formatting
        run: prettier '**/*.{js,jsx}' --check
  write-good:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Project Dependencies
        run: yarn
      - name: Validate Blog Text Style
        run: yarn run write-good
