name: Lint ModuleSite Code

# Trigger the workflow on all pull requests
on: pull_request

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v3
      - name: Install Project Dependencies
        run: yarn
      - name: Validate JavaScript Formatting
        run: yarn run format-check:js
