name: Lint ModuleSite Code

# Trigger the workflow on all pull requests, merges
# and once a day at 1:35 UTC (to check for security events)
on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]
  schedule:
    - cron: '35 1 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          # Globally caches yarn dependencies
          cache: 'yarn'
      - name: Install Project Dependencies
        run: yarn install --frozen-lockfile --immutable
      - name: Build ModuleSite
        run: yarn run build
      - name: Upload generated resources
        uses: actions/upload-artifact@v3
        with:
          name: generated
          path: src/generated
  eslint:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout PR
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          # Globally caches yarn dependencies
          cache: 'yarn'
      - name: Install Project Dependencies
        run: yarn install --frozen-lockfile --immutable
      - name: Download generated resources from build job
        uses: actions/download-artifact@v3
        with:
          name: generated
          path: src/generated
      - name: Lint JavaScript
        run: yarn run lint:js --format @microsoft/eslint-formatter-sarif --output-file eslint-results.sarif
      - name: Upload analysis results to GItHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          # Globally caches yarn dependencies
          cache: 'yarn'
      - name: Install Project Dependencies
        run: yarn install --frozen-lockfile --immutable
      - name: Validate JavaScript Formatting
        run: yarn run format-check:js
